### PR TITLE
TypeScript rewrite

### PR DESCRIPTION
**Pull request by SamuelMarks**
Nothing too crazy (like a `function`→`class` conversion). Just annotated with types, replaced `var` with `let`/`const`, moved to arrow functions, and switched to the new ES6 `export` syntax.

BTW: With arrow functions I think we can remove all the `bind`s also.

### CODE REVIEW

**Comment by SamuelMarks** [comment]
@kornelski Decided to do the crazy `function`→`class` conversion.

**Comment by kornelski** [comment]
This is a massive change, not only in the code, but also in the way it's used. 

It's nice to see the code mostly works fine with strict(er) types. However, it also has some quirky bits in the state machine that are taking advantage of class-less ad-hoc nature of JS, so some places got nicer, some got less nice.

There are some small wins in syntax, but many of them are also in ES6. 

I like TS in general, but I'm not sure if it brings enough to this codebase to be worth the churn and addition of compilation step.

**Comment by SamuelMarks** [comment]
My reasoning for the rewrite was that all the frontend frameworks I use—e.g.: Angular—are developed in TypeScript. Sure, I could write a tiny `.d.ts` for it, but I decided to go full throttle and rewrite.

Yeah, decided to use [`class` expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/class) for your quirky state machine.

You can also change the [target in the `tsconfig.json`](https://github.com/SamuelMarks/slip/blob/46f96e33b09e2dc3b3f4ad17e644b3f6afadeb36/tsconfig.json#L3) to emit `es6`.

As for the advantages of TypeScript, generally it is easier to maintain due to:
- [explicit] type safety, via annotations (including `interface`s)
- code completion (just choose an IDE that supports it)
- compile-time errors & tracing
- emit for different JavaScript versions
- improved minification

(to name just a few… [here's Ionic's list](https://ionicframework.com/docs/developer-resources/typescript/))

**Comment by SamuelMarks** [comment]
@kornelski Aww you closed this after 2.5 years

Still keen to get a TS rewrite of your library accepted…

**Comment by kornelski** [comment]
Well, nothing has changed since. It's still a small library. Survived without types so far.

**Pull request closed without merging**
